# https://github.com/tanwanimohit/deploy-react-to-ghpages

name: Deploy App

on:
  push:
    branches: [ master ] # TODO use default branch name here

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Deploy react app to github pages
      uses: tanwanimohit/deploy-react-to-ghpages@v1.0.1